name: Matrix Build 5c54064

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build for Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']  # 3 variants

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: matrix-5c54064
        run: echo "Running matrix build for Python ${{ matrix.python-version }}"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Generate build artifact
        run: |
          echo "Build output for Python version ${{ matrix.python-version }}" > build_output.txt
          echo "Timestamp: $(date)" >> build_output.txt
          echo "This file is intentionally non-empty for CI validation." >> build_output.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-5c54064-py${{ matrix.python-version }}
          path: build_output.txt
